topics:
  img_topic: "/color/video/image"
  base_frame: "checkerboard"
  dice_detection_mask_topic: "/dice_detection_mask"
  dice_detection_img_topic: "/dice_detection_img"
  dice_detection_srv_topic: "/dice_detection_pose"
  dice_face_picker_srv_topic: "/dice_face_picker"

detector:
  die_size: 0.03

  # Color detection parameters
  hue_range: [20, 40] # Yellow color range in HSV
  saturation_range: [130, 255]
  value_range: [150, 255]

  # Parameters for the blobs/dice points detector
  min_point_area: 50
  max_point_area: 600
  # max_point_area: 400
  min_inertia_ratio: 0.7
  min_circularity: 0.85
  dbscan_eps: 80.0

robot:
  robot_id: 1 # redhand
  robot_name: "ur10e"
  robot_ip: "192.168.254.100"

camera:
  1: # ROBOT 1, redhand
    K: [1578.55692, 0.0, 952.440456, 0.0, 1582.46225, 545.655012, 0.0, 0.0, 1.0]
    d: [0.07206577, 0.08106335, 0.00300317, 0.00042163, -0.40383728]
    T_w2c: [0.999831, -0.015292, -0.010167, -0.062168, 0.015271, 0.999881, -0.002154, -0.071062, 0.010198, 0.001998, 0.999946, 0.717149, 0.0, 0.0, 0.0, 1.0]
    T_c2w: [0.99983176346411353277, 0.015270867490153322504, 0.010198733719334276597, 0.055928707768535428385, -0.015292148791802741282, 0.99988114556050448129, 0.001998376623108716053, 0.06866973786284598402, -0.010166279589618847348, -0.0021536111304955182948, 0.99994599764090986714, -0.71789532944586356732, 0.0, 0.0, 0.0, 1.0]
      
  2: # ROBOT 2, black bar
    K: [1545.88237, 0.0, 946.934926, 0.0, 1555.02898, 544.959477, 0.0, 0.0, 1.0]
    d: [0.13503889, -0.28098708, 0.0003601, -0.00038133, 0.13643112]
    T_w2c: [0.999581, -0.018623, 0.022175, -0.013014, 0.019132, 0.999553, -0.022993, -0.037747, -0.021737, 0.023408, 0.999490, 0.737709, 0.0, 0.0, 0.0, 1.0 ]
    T_c2w: [0.99958028593701093475, 0.019132552425251395473, -0.021736863863309700093, 0.029766214401318560277, -0.018622422187361956217, 0.99955206952081717373, 0.023407590817813985789, 0.020219749351237219717, 0.022175099634788317405, -0.022993357163428947583, 0.99948932045777331174, -0.73791161061178430934, 0.0, 0.0, 0.0, 1.0]